- SSSOM.md
fixes #54 
However, reviewing this made me realise that this spec does not consider the case when the hash symbol appears in a value. For example:
```
mapping_source: https://github.com/INCATools/ontology-development-kit/blob/master/docs/ReleaseArtefacts.md#release-artefact-2-full-required
```
or 
```
HP:001 skos:exactMatch MP:001  https://github.com/INCATools/ontology-development-kit/blob/master/docs/ReleaseArtefacts.md#release-artefact-2-full-required
```
Ideas @cmungall @balhoff ?
> Clarify comment block in embedded mode

- model/schema/sssom.yaml
I think including `required` was a (mostly harmless) mistake?
> Removing required as a model element (it is a metamodel element)

- model/schema/sssom.yaml
https://w3id.org/linkml/recommended
has no effect on validation, json-schema generation, or python generation
tools/applications can optionally use `recommended` to issue warnings
It's not clear if we can come up with universal guidelines for what is required, in future we may want to define profiles. For now I have added subject and object label since this makes the mappings more approachable to human users.
> Making some fields recommended

- model/docs/spec.md
I find "metadatdata" oddly satisfying but consider it a typo.
> metadatdata typo

- model/schema/sssom.yaml
Fixes https://github.com/mapping-commons/sssom/issues/134
Note that this is important in particular for our automated mapping pipelines to trace mappings that are merged from one mapping set to another.
> Adding mapping_source to SSSOM

- model/schema/sssom.yaml
Fixes #143
This removes the `match_term_type` and its corresponding   enums, replacing it by two seperate (subject and object match types)
> Replacing `match_term_type` by `subject` and `object_type`

- model/schema/sssom.yaml
See also #150
After some deliberations with some of you, this will be the hopefully last major breaking change in SSSOM.
> Breaking change: Replacing `match_type` with `mapping_justification`

- src/linkml/sssom.yaml
This is an oversight. w3ids must be https, and should be: https://w3id.org/
> Change w3id.org to https

- .github/workflows/deploy_documentation.yml
- mkdocs.yml
~- [ ] `make test` has been run locally~
~- [ ] tests have been added/updated (if applicable)~
~- [ ] [CHANGELOG.md](https://github.com/mapping-commons/sssom/blob/0.9.0/CHANGELOG.md) has been updated.~
> Fixes Edit links in documentations dont work #190

- src/docs/mapping-predicates.md
Disclaimers:
- I did this quickly, and probably missed some typos
- the overall organization and content of this document look good, but I did not assess those
> fixed some typos

- src/docs/spec.md
> Fix broken linke in docs

- src/sssom_schema/schema/sssom_schema.yaml
Resolves #219 
This PR adds the mapping_set_title element, which allows to capture display names for mapping sets.
> Add mapping_set_title

- src/sssom_schema/schema/sssom_schema.yaml
Resolves [#238, #239]
Add two text slots, `registry_title` and `registry_description`, to mapping registry class.
> Add registry title and registry description slots

- src/docs/chaining_rules.md
Fixes #79 
This PR is intended to document basic chaining rules that can be applied with SSSOM. 
These are only trivial, structural rules, and does not replace more sophisticated reasoning or probabilistic reconciliation.
> Document chaining rules

- src/sssom_schema/schema/sssom_schema.yaml
> Improve documentation for subject and object categories

- src/docs/chaining_rules.md
This PR updates the documentation to propose new inversion (“flipping”) rules for the cross-species predicates defined in the “semantic mapping vocabulary” (SEMAPV).
Specifically, it proposes that `semapv:crossSpeciesExactMatch` can be directly inverted, and that `semapv:crossSpeciesNarrowMatch` and `semapv:crossSpeciesBroadMatch` are mutually inverse. This follows the logic of the `skos:{exact,narrow,broad}Match` predicates upon which those cross-species variants are based.
`semapv:crossSpeciesCloseMatch` is _not_ listed on purpose; the predicate is to be implicitly considered as “non-invertible”.
> Add inversion rules for SEMAPV cross-species predicates.

- .github/ISSUE_TEMPLATE/new_sssom_element.md
- .github/pull_request_template.md
> Make adding a concrete SSSOM example part of the new element request

- src/sssom_schema/schema/sssom_schema.yaml
See also #266 
This PR adds a bunch of examples of using the `see_also` property correctly. I also checked if it works - they show up in the RDF serialisations of the LinkML schema.
> Add some examples of using see_also to SSSOM schema

- .github/pull_request_template.md
This PR extends the pull request template to make adding a working example to a metadata field required.
> Making adding a link to a working example required when adding a new field

- src/sssom_schema/schema/sssom_schema.yaml
The semapv namespace is wrongly documented in the LinkML model.
Instead of `https://w3id.org/semapv/` it should be `https://w3id.org/semapv/vocab`, see SEMAPV:
https://github.com/mapping-commons/semantic-mapping-vocabulary/blob/main/semapv.owl
e.g.:
https://w3id.org/semapv/vocab/CaseNormalization
> Fix semapv namespace in SSSOM schema

- Makefile
- src/sssom_schema/context/sssom_schema.context.jsonld
- src/sssom_schema/context/sssom_schema.jsonld
This enables packages that use `sssom-schema` as a dependency to use context files within this package rather than doing a `wget` which is not efficient.
This will be address : https://github.com/mapping-commons/sssom-py/issues/375 via https://github.com/mapping-commons/sssom-py/pull/382
> Package context files through `make`

- mkdocs.yml
- src/docs/update.md
> Release process documented

- src/sssom_schema/schema/sssom_schema.yaml
@gouttegd noticed that while you can provide `mapping_tool` on `MappingSet` level, you cant declare `mapping_tool_version`. This was a oversight on my part, so no need for a large review.
> Add mapping_set_version to MappingSet metadata

- mkdocs.yml
- src/docs/glossary.md
- src/docs/mapping-justifications.md
- src/docs/matching-tool-implementation-guide.md
Resolves #297 
This PR adds a provisional guide for matching tool developers that want to include SSSOM metadata into their pipelines.
> Add guide for tool implementors

- src/sssom_schema/schema/sssom_schema.yaml
Resolves #293 
A property (publication_date) was defined in SSSOM, but was not added to the SSSOM mapping and mapping set data model. Since a very similar property (mapping_date) was already defined, this change is considered a bugfix, rather than an added feature.
> Fix publication_date

- src/sssom_schema/schema/sssom_schema.yaml
Resolves #304 
In this PR, we 
- clarify the scope of a number of SSSOM properties (e.g author, reviewer and creator_id properties are clarified to be URIs, rather than "strings")
- Drop the use of syntactic concerns such "pipe-seperated" which do not belong in a general spec
- fix some minor typos
> Clarifying descriptions of various properties

- src/docs/mapping-justifications.md
In response to a request on slack, adding more details to the docs on how to curation mapping justifications that are manually curated.
> Add details on manual mapping curation in docs

- CHANGELOG.md
- src/docs/spec.md
This PR adds a recommendation that
1) the keys in the YAML metadata block (in both "embedded" and “external” modes) SHOULD be sorted in the same order as the corresponding slots are listed in the definition of the [MappingSet class](https://mapping-commons.github.io/sssom/MappingSet/) in the SSSOM model;
2) the keys in the `curie_map` dictionary (i.e. the prefix names) SHOULD be sorted by alphabetical order.
This is an alternative PR to #319 (which proposed to sort the YAML metadata block by alphabetical order). “Spec order“ is not the current behaviour of `sssom-py`, but is preferred at least by @matentzn.
Of note, since `curie_map` is currently _not_ part of the model (and therefore not listed in the definition of `MappingSet`), the position of the `curie_map` key would be unspecified …
> Recommend that YAML keys be sorted by "spec order".

- Makefile
- src/doc-templates/class.md.jinja2
- src/doc-templates/class_diagram.md.jinja2
- src/doc-templates/common_metadata.md.jinja2
- src/doc-templates/index.md.jinja2
- src/doc-templates/slot.md.jinja2
Resolves #332 
This PR added in the relevant/necessary base jinja templates (as is) from the linkml library: https://github.com/linkml/linkml/tree/main/linkml/generators/docgen in a folder called `src/doc-templates`. Now the jinja templates can be edited here, in order to customize the class/slot/index, etc. documentation pages to look like how we want them to look. The downstream makefile target which uses linkml `gen-doc` is `make gendoc` and that has been updated too.
> Add ability to customize documentation pages using jinja templates

- .github/workflows/deploy_documentation.yml
Related to #332 #333 
This PR ensures that the changes provided by @sujaypatil96 in #333 are also taken into account by the automatic SSSOM docs deploy system.
> Ensure that github action workflow deploys custom docs

- src/docs/spec.md
Fixes #340
by adding the correct link.
> Fix link to schema in overview document

- Makefile
Updating gendoc command to copy the whole docs directory into the docs dir, rather than just the top level. The current behaviour made a lot of pages inaccessible.
> Update gendoc to copy subdirectories

- src/sssom_schema/schema/sssom_schema.yaml
Resolves https://github.com/mapping-commons/sssom-py/issues/512
The documentation for "entity references" is largely confusing, and leading, in its current form, to the expectation that metadata fields types with these can be _either_ a CURIE _or_ a full URI.
This is not quite right: in the TSV serialistion, as well as JSON, we expect the values to be CURIE-strings. This PR documents this design decision, but, as @joeflack4 puts it rightfully, this has a bit of a "smell" to it. Not sure what the right thing is here, but this documentation here is certainly better than not having it.
> Update documentation for entity reference to clarify CURIE/URI type

- CHANGELOG.md
- src/docs/spec-model.md
- src/sssom_schema/schema/sssom_schema.yaml
Resolves [#305]
This PR finalises the fix to #305, by explicitly specifying, directly within the LinkML model, which slots are considered “propagatable” (previously this was only informally described in the spec, since #368). This is done by:
* adding a “metamodel extension class“ (`sssom:Propagatable`) with a single boolean-ranged attributed `propagated`;
* amending the slots that must be considered propagatable by making them instantiate the `sssom:Propagatable` extension.
> Model propagatable slots

- CHANGELOG.md
- src/sssom_schema/schema/sssom_schema.yaml
Resolves #372
The description of the `confidence`, `semantic_similarity_score`, and `similarity_score` slots says that those slots expect a value between 0 and 1, but the model does not enforce that. LinkML provides a way to formalise this kind of value constraints (which could then be automatically enforced by a runtime that is aware of those constraints), so we do exactly that here: we add `minimum_value` and `maximum_value` constraints to the aforementioned slots.
> Add min/max value constraints to score and confidence slots.

- .github/pull_request_template.md
- CONTRIBUTING.md
This PR updates the CONTRIBUTING.md document to add a section about how to locally run the test suite, and especially how to locally run SSSOM-Py’s test suite, since changes to SSSOM’s LinkML schema can negatively impact the Python implementation.
It also updates the pull request template to add a checkbox to remind contributors that any change to the LinkML schema should be tested against SSSOM-Py (or rather, SSSOM-Py should be tested against the new schema).
> Document testing SSSOM-Py against a development version of the schema.

- src/docs/presentations.md
This commit adds the talk given at the 15th ICBO (July 2024), about the use of SSSOM to overhaul the bridges between Uberon and the taxon-specific anatomy ontologies.
(Note: At some point the link to the paper should be replaced by a link to the official proceedings of the conference, but those are not available yet.)
- ~[ ] `make test` has been run locally~
- ~[ ] tests have been added/updated (if applicable)~
- ~[ ] [CHANGELOG.md](https://github.com/mapping-commons/sssom/blob/master/CHANGELOG.md) has been updated.~
> Add the Uberon/SSSOM talk at ICBO 2024.

- src/doc-templates/index.md.jinja2
> update linkml docs index page

- src/sssom_schema/schema/sssom_schema.yaml
See #392 
this PR adds examples to most slots related to mappings, and updates some descriptions.
> Add many examples to schema and update some descriptions

- CHANGELOG.md
- examples/schema/composite-entities.sssom.tsv
- src/sssom_schema/schema/sssom_schema.yaml
Resolves #402
This PR adds a new value `composed entity` to the `EntityType` enumeration to indicate, as proposed in #402, that an ID is intended to represent a composed (aka “complex”, aka “post-coordinated”) entity that involves several individual entities.
> Add 'composed entity' value to the EntityType enum.

- src/sssom_schema/schema/sssom_schema.yaml
There must be a better way to do this in LinkML by now!
This is adding a number of newer justifications to the validation rules of the schema.
> Add some missing justifications

- CHANGELOG.md
- src/docs/spec-model.md
- src/sssom_schema/schema/sssom_schema.yaml
Resolves [#411]
- ~~[ ] provide a full, working and valid example in `examples/`~~
- ~~[ ] provide a link to the related GitHub issue in the `see_also` field of the linkml model~~
- ~~[ ] provide a link to a valid example in the `see_also` field of the linkml model~~
This PR adds the `similarity_measure` slot to the `MappingSet` class, as a propagatable slot. It should be quite common that all `similarity_score` for all mappings in a set are determined using the same measure, so it makes sense to allow setting the measure once and for all at the set level, without having to repeat that information for all individual mappings.
> Allow using `similarity_measure` at the set level.

- .github/workflows/main.yaml
The old one is no longer supported.
> Upgrade the cache version in main Github action

- src/sssom_schema/schema/sssom_schema.yaml
Fixes #417
This PR simply adds links to the semap docs and OLS links to the mapping_justification slot. This will cause these links to show up on https://mapping-commons.github.io/sssom/mapping_justification/
> Add links to semapv docs to sssom_schema.yaml mapping_justification slot

- .github/workflows/build.yml
- .github/workflows/deploy_documentation.yml
actions/cache@v2 is not supported by GitHub actions anymore.
> Update more action to using actions/cache@v4

- CHANGELOG.md
- src/sssom_schema/schema/sssom_schema.yaml
Resolves [#422]
The `see_also` slot is explicitly described as expecting URL values, so there should not be any reason for it to be typed as `xsd:string`. We re-type it as a `xsd:anyURI` instead.
> Change type of `see_also` to `xsd:anyURI`.

- src/sssom_schema/schema/sssom_schema.yaml
Clarifying the intended use of subject and object match field in the main slot descriptions.
Fixes #413 
Make it a bit clearer how subject and `object_match_field` are supposed to be used.
@nichtich does this work for you?
> Add additional docs for subject and object match fields

- src/docs/spec-formats-owl.md
Nondesruptive change (just a correction in the documentation)
> Correct typo

- CHANGELOG.md
- examples/schema/version.sssom.tsv
- src/docs/spec-model.md
- src/sssom_schema/schema/sssom_schema.yaml
Resolves [#439]
This PR adds the new `sssom_version` set-level slot suggested in #439.
Contrary to the original suggestion of using a `xsd:string`-typed slot, it uses a enum-typed slot, with a new `sssom_version_enum` slot whose values represent the different versions of the specification (for now, the current 1.0 version and the upcoming 1.1). This should allow implementations to very easily check whether the version found in a set is one they support or not: if the value is not one of the “permissible values”, then either it’s a completely bogus value, or it’s one from a more recent version of the model than the one supported by the implementation.
It also add a …
> Add a `sssom_version` slot

- .github/pull_request_template.md
- CONTRIBUTING.md
This PR updates the contributing guidelines to explain that changes to the model in the 1.x branch should be ideally limited to adding optional slots, and that added slots should be tagged with the `added_in` annotation to indicate the version of the spec they will be introduced in.
Arguably this could/should have been done as part of the PR in which the `sssom_version` slot was introduced (#440).
> Update contributing guidelines to mention backwards compatibilty

- src/sssom_schema/schema/sssom_schema.yaml
Resolves [#344]
- ~~[ ] `docs/` have been added/updated if necessary~~ not needed, doc is in the model
- ~~[ ] tests have been added/updated (if applicable)~~ nothing to test
- ~~[ ] [CHANGELOG.md](https://github.com/mapping-commons/sssom/blob/master/CHANGELOG.md) has been updated.~~ not needed, this is a clarification only
There is not supposed to be any link between `author_id` and `author_label`. In particular, `author_label[n]` is _not_ intended to be the human-friendly label of `author_id[n]`.
This has seemingly always been the intention (see notably this comment: https://github.com/mapping-commons/sssom/issues/344#issuecomment-1893588484) but has never been made explicit in the schema, which is what this PR is about.
Likewise for `reviewer_id`/`reviewer_label` and …
> Clarify the absence of link between author_id and author_label.

- CHANGELOG.md
- examples/schema/mapping_tool_id.sssom.tsv
- src/sssom_schema/schema/sssom_schema.yaml
Resolves #449 
This PR is adding mapping_tool_id as an entity reference to the SSSOM model. I have also included a note that if possible, this slot should be preferred over the less formal `mapping_tool` slot.
cc @nichtich @gouttegd
> Add mapping_tool_id slot to model

- src/sssom_schema/schema/sssom_schema.yaml
Related to https://github.com/mapping-commons/sssom/discussions/454
- ~~[ ] `docs/` have been added/updated if necessary~~
- ~~[ ] [CHANGELOG.md](https://github.com/mapping-commons/sssom/blob/master/CHANGELOG.md) has been updated.~~
This PR ensures that all enum values (_except_ for the `mapping_cardinality_enum`) throughout the LinkML model have a property assigned to them. This is important for RDF serialisation, so that all enum values are consistently rendered as resource identifiers, instead of having some values being rendered as resource identifiers and some values being rendered as string literals.
I normally agree with @nichtich ’s sentiment (expressed in #450) that we should as much as possible reuse existing properties …
> Assign a property to ALL enum values.

- src/doc-templates/slot.md.jinja2
As pointed out by @gouttegd in https://github.com/mapping-commons/sssom/issues/468, this template makes too many assumptions. A slot is not _generally_ optional or required, it is optional or required in the context of a specific class.
Fixes #468
> Remove required/optional flag from slot pages

- src/sssom_schema/schema/sssom_schema.yaml
The description of the `subject_match_field` slot is written as a folded scalar block (`> ...`) with no explicit chomping indicator. As a result, the last newline character is interpreted as being part of the description.
This in turn messes with the formatting of the slot table on SSSOM's index page, because the row for the `subject_match_field` slot is spread over two lines (since the description cell contains a newline character):
```
| subject_match_field | description...
entity reference | rdfs:label |
```
instead of the expected:
```
| subject_match_field | description... | entity reference | rdfs:label |
```
This PR adds an explicit chomping indicator (`>-`) to prevent the terminating newline character from being taken as part of the scalar value.
Likewise for `object_match_field`.
> Fix chomping of description blocks for subject|object_match_field.

- CHANGELOG.md
- examples/schema/cardinality-scope-empty.sssom.tsv
- examples/schema/cardinality-scope-predicate+object_source.sssom.tsv
- examples/schema/cardinality-scope-predicate.sssom.tsv
- src/docs/spec-model.md
- src/sssom_schema/schema/sssom_schema.yaml
Resolves [#467]
This PR adds a new mapping record slot called `cardinality_scope`, intended to precise the meaning of the value of the `mapping_cardinality` slot.
If empty, it means that the cardinality is relative to the entire set (which corresponds to the current definition of `mapping_cardinality`, and therefore ensures backwards compatibility). If non-empty, it is expected to be a list of slots that are used to define the subset (the "scope") of mapping records in which the cardinality has been computed.
For example, a cardinality scope of (`predicate_id`, `object_source`) means that the cardinality is computed over the subset of mapping records that have the …
> Add `cardinality_scope` slot.

- CHANGELOG.md
- examples/schema/curation_rule-propagated.sssom.tsv
- examples/schema/curation_rule_text-propagated.sssom.tsv
- src/doc-templates/index.md.jinja2
- src/docs/spec-model.md
- src/sssom_schema/schema/sssom_schema.yaml
- Make curation_rule_* slots propagatable 
- Remove a confusing part of the curation rule description.
Resolves #464 
If you are proposing a change to the SSSOM metadata model, you must
> Make curation_rule_* slots propagatable

- src/sssom_schema/schema/sssom_schema.yaml
- ~~[ ] [CHANGELOG.md](https://github.com/mapping-commons/sssom/blob/master/CHANGELOG.md) has been updated.~~ Already covered by previous changes
The `added_in` annotation is used to indicate that a slot has been introduced in a specific version of the specification. For now, that annotation is only used in the model-wide definition of slots, which means it can only indicate when a brand new slot has been introduced – it can not be used to indicate that a pre-existing slot has been added to a class in which it was not used before.
For example, the `similarity_measure` slot has existed since before 1.0, but has been only been added to the `MappingSet` class for version 1.1. Currently that information is _not_ contained in the model, …
> Annotate class-specific usage of slot with `added_in`.

- .github/workflows/pypi-publish.yaml
- CHANGELOG.md
Workflow now triggers on published and prereleased events, sets PEP 440-compliant version for prereleases, and adds 'skip-existing' to PyPI publish step. Improves handling of pre-release publishing and artifact management.
Resolves #490
> Update PyPI publish workflow for prereleases
