mapping-commons/sssom

- SSSOM.md
- examples/embedded/mp-hp-exact-0.0.1.tsv
- examples/external/mp-hp-exact-0.0.1-meta.yaml
> WIP: Metadata to YAML

- SSSOM.md
> Fix skos:narrowMatch and skos:broadMatch

- SSSOM.md
> Adding filename recommendation

- README.md
the existing link is to a soft redirect
or use w3id?
> link to spec

- .github/workflows/build.yml
> issue 115+116 - II

- .github/workflows/build.yml
Reverts mapping-commons/sssom#120
> Revert "issue 115+116 - II"

- .github/workflows/main.yaml
- .github/workflows/pypi-publish.yaml
> deploy using gh action

- .github/workflows/deploy_documentation.yml
> Corrected path for doc generation

- src/sssom_schema/schema/sssom_schema.yaml
> Fixing hasDbXref reference in examples

- src/docs/spec.md
> Add link to contextualize "drive-by curation"

- src/sssom_schema/schema/sssom_schema.yaml
Change text that might have been copy/pasted
> Fix typo in schema

- src/docs/events/mc2023.md
QUESTION: Is there a remote participation option? If so, can you mention in this document how to find out how to join? (Don't put the Zoom URL on this public page, of course.)
> minor improvements to some text and formatting

- .github/workflows/qc.yml
> Update sssom-schema as well

- src/sssom_schema/schema/sssom_schema.yaml
Update sssom_schema.yaml
- Updated description for match_string. Corrected plurality issue.
Apologies, skipping this because this is a very small issue / PR.
<details><summary>Boilerplate</summary>
<p>
</p>
</details>
> `match_string` description update

- src/sssom_schema/schema/sssom_schema.yaml
This is a hotfix for a problem that I have yet to understand..
> Remove slot_uri mapping from literal mapping

- src/sssom_schema/schema/sssom_schema.yaml
Made a mistake here #356 Thanks for catching @hrshdhgd
> Change slot_uri for literal

- src/docs/index.md
The main update here is to the list of contributors, and the formal definition separation of editor and steering committee. I do understand that concept of "steering committee" has never been formally discussed - as co-founder and main developer I am taking the liberty to define this group, that has effectively operated but not named so far, now.
> Update the landing page, and list of contributors, steering committee

- CHANGELOG.md
Just an oversight, please approve and merge whoever sees this!
> Add SSSOM v 1.0.0 to CHANGELOG.md

- mkdocs.yml
- src/doc-templates/slot.md.jinja2
This renders the slot/column level docs a bit more nicely
> Update the documentation templates for slots

- src/docs/presentations.md
> Add SSSOM RDA plenary talk to presentations.md

- .github/workflows/qc.yml
> Update ODK version in QC action

- .github/pull_request_template.md
> Add additional model changes instruction to pull_request_template.md

- examples/schema/curation_rule-propagated.sssom.tsv
- examples/schema/curation_rule.sssom.tsv
- examples/schema/curation_rule_text-propagated.sssom.tsv
- examples/schema/curation_rule_text.sssom.tsv
- examples/schema/issue_tracker.sssom.tsv
- examples/schema/issue_tracker_item.sssom.tsv
Sorry @gouttegd the upside of merging the broken file was - I fixed all the wrong ones at once.
This way the copy-paste approach will make sure I wont get it wrong again.
> Make sure creator_id is formatted in the multivalued syntax in all examples
